<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Product_specification_fmp;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductspecfmpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $specificationfmp = [
            [
                'product_id' => 2,
                'harga' => 360000000,
                'type_name' => 'FMP-101',
                'dry_solids_min' => 3,
                'dry_solids_max' => 5,
                'dimension_l' => 1904,
                'dimension_w' => 862,
                'dimension_h' => 1160,
                'power_kw' => 0.44,
                'opex_chemical_min' => 0.018,
                'opex_chemical_max' => 0.05,
                'opex_electrical_min' => 0.09,
                'opex_electrical_max' => 0.15,

                'quot_pd_flush_water' =>  '24L/h',
                'quot_sc_specification_length' =>  'Φ100×990 (mm)',
                'quot_sc_quantity' => '1',
                'quot_sc_motorpower' =>  '0.18kW×1',
                'quot_fmt_dimension' => 'LL330×W330×H550 (mm)',
                'quot_fmt_volume' =>  'About 59 L',
                'quot_fmt_motorpower' =>  '0.18kW',
                'quot_equipment_weight' =>  '200 Kg',
                'quot_operating_weight' =>  '300 Kg',
                'quot_work_time' =>  '2 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 390000000,
                'type_name' => 'FMP-102',
                'dry_solids_min' => 6,
                'dry_solids_max' => 10,
                'dimension_l' => 1904,
                'dimension_w' => 892,
                'dimension_h' => 1160,
                'power_kw' => 0.62,
                'opex_chemical_min' => 0.036,
                'opex_chemical_max' => 0.1,
                'opex_electrical_min' => 0.06,
                'opex_electrical_max' => 0.06,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 310000000,
                'type_name' => 'FMP-131',
                'dry_solids_min' => 6,
                'dry_solids_max' => 12,
                'dimension_l' => 2715,
                'dimension_w' => 822,
                'dimension_h' => 1360,
                'power_kw' => 0.55,
                'opex_chemical_min' => 0.036,
                'opex_chemical_max' => 0.12,
                'opex_electrical_min' => 0.05,
                'opex_electrical_max' => 0.07,

                'quot_pd_flush_water' =>  '28L/h',
                'quot_sc_specification_length' =>  'Φ130×1150 (mm)',
                'quot_sc_quantity' => '1',
                'quot_sc_motorpower' =>  '0.18kW×1',
                'quot_fmt_dimension' => 'L330×W330×H550 (mm)',
                'quot_fmt_volume' =>  'About 59 L',
                'quot_fmt_motorpower' =>  '0.18kW',
                'quot_equipment_weight' =>  '408 Kg',
                'quot_operating_weight' =>  '758 Kg',
                'quot_work_time' =>  '3 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 330000000,
                'type_name' => 'FMP-132',
                'dry_solids_min' => 12,
                'dry_solids_max' => 24,
                'dimension_l' => 2715,
                'dimension_w' => 1128,
                'dimension_h' => 1360,
                'power_kw' => 0.73,
                'opex_chemical_min' => 0.072,
                'opex_chemical_max' => 0.24,
                'opex_electrical_min' => 0.03,
                'opex_electrical_max' => 0.07,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 370000000,
                'type_name' => 'FMP-201',
                'dry_solids_min' => 9,
                'dry_solids_max' => 15,
                'dimension_l' => 2906,
                'dimension_w' => 964,
                'dimension_h' => 1335,
                'power_kw' => 0.7,
                'opex_chemical_min' => 0.054,
                'opex_chemical_max' => 0.15,
                'opex_electrical_min' => 0.05,
                'opex_electrical_max' => 0.03,

                'quot_pd_flush_water' =>  '32L/h',
                'quot_sc_specification_length' =>  'Φ200×1660 (mm)',
                'quot_sc_quantity' => '1',
                'quot_sc_motorpower' =>  '0.37kW×1',
                'quot_fmt_dimension' => 'L380×W380×H700 (mm)',
                'quot_fmt_volume' =>  'About 100 L',
                'quot_fmt_motorpower' =>  '0.25kW',
                'quot_equipment_weight' =>  '400 Kg',
                'quot_operating_weight' =>  '750 Kg',
                'quot_work_time' =>  '3 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 350000000,
                'type_name' => 'FMP-202',
                'dry_solids_min' => 18,
                'dry_solids_max' => 30,
                'dimension_l' => 2906,
                'dimension_w' => 1112,
                'dimension_h' => 1335,
                'power_kw' => 0.95,
                'opex_chemical_min' => 0.108,
                'opex_chemical_max' => 0.3,
                'opex_electrical_min' => 0.03,
                'opex_electrical_max' => 0.03,

                'quot_pd_flush_water' =>  '64L/h',
                'quot_sc_specification_length' =>  'Φ200×1660 (mm)',
                'quot_sc_quantity' => '2',
                'quot_sc_motorpower' =>  '0.37kW×2',
                'quot_fmt_dimension' => 'L430×W430×H700 (mm)',
                'quot_fmt_volume' =>  'About 120 L',
                'quot_fmt_motorpower' =>  '0.55kW',
                'quot_equipment_weight' =>  '600 Kg',
                'quot_operating_weight' =>  '900 Kg',
                'quot_work_time' =>  '3 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 480000000,
                'type_name' => 'FMP-203',
                'dry_solids_min' => 27,
                'dry_solids_max' => 45,
                'dimension_l' => 3087,
                'dimension_w' => 1202,
                'dimension_h' => 1465,
                'power_kw' => 1.2,
                'opex_chemical_min' => 0.162,
                'opex_chemical_max' => 0.45,
                'opex_electrical_min' => 0.03,
                'opex_electrical_max' => 0.04,

                'quot_pd_flush_water' =>  '96L/h',
                'quot_sc_specification_length' =>  'Φ200×1150 (mm)',
                'quot_sc_quantity' => '1',
                'quot_sc_motorpower' =>  '1.66kW×2',
                'quot_fmt_dimension' => 'L330×W330×H550 (mm)',
                'quot_fmt_volume' =>  'About 96 L',
                'quot_fmt_motorpower' =>  '1.55kW',
                'quot_equipment_weight' => '600 Kg',
                'quot_operating_weight' => '900 Kg',
                'quot_work_time' =>  '3 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 500000000,
                'type_name' => 'FMP-301',
                'dry_solids_min' => 30,
                'dry_solids_max' => 50,
                'dimension_l' => 3446,
                'dimension_w' => 997,
                'dimension_h' => 1949,
                'power_kw' => 1.38,
                'opex_chemical_min' => 0.18,
                'opex_chemical_max' => 0.5,
                'opex_electrical_min' => 0.03,
                'opex_electrical_max' => 0.03,

                'quot_pd_flush_water' =>  '40L/h',
                'quot_sc_specification_length' =>  'Φ300×2260 (mm)',
                'quot_sc_quantity' => '1',
                'quot_sc_motorpower' =>  '0.75kW×1',
                'quot_fmt_dimension' => 'L500×W500×H1000 (mm)',
                'quot_fmt_volume' =>  'About 250 L',
                'quot_fmt_motorpower' =>  '0.55kW',
                'quot_equipment_weight' =>  '1000 Kg',
                'quot_operating_weight' =>  '1600 Kg',
                'quot_work_time' =>  '4 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 410000000,
                'type_name' => 'FMP-302',
                'dry_solids_min' => 60,
                'dry_solids_max' => 100,
                'dimension_l' => 3576,
                'dimension_w' => 1421,
                'dimension_h' => 1950,
                'power_kw' => 2.13,
                'opex_chemical_min' => 0.36,
                'opex_chemical_max' => 1,
                'opex_electrical_min' => 0.02,
                'opex_electrical_max' => 0.03,

                'quot_pd_flush_water' =>  '80L/h',
                'quot_sc_specification_length' =>  'Φ300×2260 (mm)',
                'quot_sc_quantity' => '2',
                'quot_sc_motorpower' =>  '0.75kW×2',
                'quot_fmt_dimension' => 'L700×W700×H1000 (mm)',
                'quot_fmt_volume' =>  'About 490 L',
                'quot_fmt_motorpower' =>  '0.75kW',
                'quot_equipment_weight' =>  '1500 Kg',
                'quot_operating_weight' =>  '2300 Kg',
                'quot_work_time' =>  '4 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 420000000,
                'type_name' => 'FMP-303',
                'dry_solids_min' => 90,
                'dry_solids_max' => 150,
                'dimension_l' => 3757,
                'dimension_w' => 1638,
                'dimension_h' => 1950,
                'power_kw' => 2.88,
                'opex_chemical_min' => 0.54,
                'opex_chemical_max' => 1.5,
                'opex_electrical_min' => 0.02,
                'opex_electrical_max' => 0.02,

                'quot_pd_flush_water' =>  '120 L/h',
                'quot_sc_specification_length' =>  'Φ300×2260 (mm)',
                'quot_sc_quantity' => '3',
                'quot_sc_motorpower' =>  '0.75kW×3',
                'quot_fmt_dimension' => 'L850×W850×H1000 (mm)',
                'quot_fmt_volume' =>  'About 650 L',
                'quot_fmt_motorpower' =>  '1.1kW',
                'quot_equipment_weight' =>  '2000 Kg',
                'quot_operating_weight' =>  '3000 Kg',
                'quot_work_time' =>  '3 month',
                            
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'product_id' => 2,
                'harga' => 430000000,
                'type_name' => 'FMP-401',
                'dry_solids_min' => 90,
                'dry_solids_max' => 150,
                'dimension_l' => 5080,
                'dimension_w' => 1536,
                'dimension_h' => 2386,
                'power_kw' => 1.93,
                'opex_chemical_min' => 0.54,
                'opex_chemical_max' => 1.5,
                'opex_electrical_min' => 0.01,
                'opex_electrical_max' => 0.02,

                'quot_pd_flush_water' =>  '80L/h',
                'quot_sc_specification_length' =>  'Φ400×3255 (mm)',
                'quot_sc_quantity' => '1',
                'quot_sc_motorpower' =>  '1.1kW',
                'quot_fmt_dimension' => 'L850×W850×H1355 (mm)',
                'quot_fmt_volume' =>  'About 980 L',
                'quot_fmt_motorpower' =>  '1.1kW',
                'quot_equipment_weight' =>  '2400 Kg',
                'quot_operating_weight' =>  '3900 Kg',
                'quot_work_time' =>  '4 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 440000000,
                'type_name' => 'FMP-402',
                'dry_solids_min' => 180,
                'dry_solids_max' => 300,
                'dimension_l' => 5080,
                'dimension_w' => 1611,
                'dimension_h' => 2386,
                'power_kw' => 3.03,
                'opex_chemical_min' => 1.08,
                'opex_chemical_max' => 3,
                'opex_electrical_min' => 0.01,
                'opex_electrical_max' => 0.02,

                'quot_pd_flush_water' =>  '160L/h',
                'quot_sc_specification_length' =>  'Φ400×3255 (mm)',
                'quot_sc_quantity' => '2',
                'quot_sc_motorpower' =>  '1.5kW×2',
                'quot_fmt_dimension' => 'L1000×W1000×H1400 (mm)',
                'quot_fmt_volume' =>  'About 1400 L',
                'quot_fmt_motorpower' =>  '1.5kW',
                'quot_equipment_weight' =>  '3000 Kg',
                'quot_operating_weight' =>  '4500 Kg',
                'quot_work_time' =>  '4 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'harga' => 450000000,
                'type_name' => 'FMP-403',
                'dry_solids_min' => 270,
                'dry_solids_max' => 600,
                'dimension_l' => 5642,
                'dimension_w' => 2116,
                'dimension_h' => 2379,
                'power_kw' => 4.13,
                'opex_chemical_min' => 1.62,
                'opex_chemical_max' => 6,
                'opex_electrical_min' => 0.01,
                'opex_electrical_max' => 0.02,

                'quot_pd_flush_water' =>  '240L/h',
                'quot_sc_specification_length' =>  'Φ400×3255 (mm)',
                'quot_sc_quantity' => '3',
                'quot_sc_motorpower' =>  '1.5kW×3',
                'quot_fmt_dimension' => 'L2000×W1000×H1400 (mm)',
                'quot_fmt_volume' =>  'About 2800 L',
                'quot_fmt_motorpower' =>  '1.1kWx2',
                'quot_equipment_weight' =>  '5320 Kg',
                'quot_operating_weight' =>  '8220 Kg',
                'quot_work_time' =>  '4 month',

                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'floater_kubikasi' => 1.936,
                'motor_kubikasi' => 1.125,
                'floater_kg' => 484,
                'motor_kg' => 281.25,
            ]
        ];
        

        foreach ($specificationfmp as $mps) {
            Product_specification_fmp::create($mps);
        }
    }
}




